# Generated by Django 4.2.21 on 2026-08-06 01:24

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menor valor aparece primero.')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menor valor aparece primero.')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='programs/covers/')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Resumen breve para listados y tarjetas.', max_length=300)),
                ('full_description', models.TextField(blank=True)),
                ('youtube_url', models.URLField(help_text='Enlace completo de YouTube (watch, youtu.be, embed o shorts).', max_length=500, validators=[common.validators.validate_youtube_url])),
                ('youtube_video_id', models.CharField(blank=True, editable=False, help_text='Extraído automáticamente de youtube_url.', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Opcional. Si se deja vacío, puede usarse la miniatura de YouTube.', max_length=500)),
                ('access_level', models.CharField(choices=[('free', 'Gratuito'), ('plan1', 'Plan de membresía 1'), ('plan2', 'Plan de membresía 2'), ('all_paid', 'Todos los planes pagos')], default='free', help_text='Nivel de membresía requerido para ver este video.', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menor valor aparece primero.')),
                ('duration_label', models.CharField(blank=True, help_text='Ej: "12:34". Texto libre, no se calcula automáticamente.', max_length=20)),
                ('publication_date', models.DateTimeField(blank=True, help_text='Fecha de publicación (puede programarse a futuro).', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='catalog.category')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='catalog.program')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['display_order', '-publication_date', 'id'],
            },
        ),
    ]
