# Generated by Django 4.2.21 on 2026-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_favorite_videoprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='access_level',
            field=models.CharField(choices=[('free', 'Gratuito'), ('plan1', 'Plan de membresía 1'), ('plan2', 'Plan de membresía 2'), ('plan3', 'Plan de membresía 3'), ('all_paid', 'Todos los planes pagos')], default='free', help_text='Nivel de membresía requerido para ver este video.', max_length=20),
        ),
    ]
