# Generated by Django 4.2.21 on 2026-10-02 02:52

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_video_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, help_text='Es la imagen que ven, con el candado encima, quienes todavía no tienen acceso a este video. Se descarga sola de YouTube la primera vez que se guarda el video; podés reemplazarla subiendo otra imagen.', upload_to=catalog.models.video_poster_upload_to, verbose_name='Imagen de portada (videos bloqueados)'),
        ),
    ]
