# Generated by Django 4.2.21 on 2026-08-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membershipplan',
            index=models.Index(fields=['is_active'], name='memberships_is_acti_01d49e_idx'),
        ),
    ]
