# Generated by Django 4.2.21 on 2026-08-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membershipplan_memberships_is_acti_01d49e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='badge',
            field=models.CharField(blank=True, help_text='Etiqueta superpuesta arriba de la tarjeta (ej. "Más recomendado"). Vacío = sin etiqueta.', max_length=40),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Texto del botón (ej. "Empezar alivio"). Vacío = "Sumarme".', max_length=60),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Título grande de la tarjeta (ej. "Alivio Lumbar"). Si se deja vacío, se usa el nombre.', max_length=150),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='visual_variant',
            field=models.CharField(choices=[('default', 'Estándar (tarjeta blanca)'), ('highlighted', 'Destacado (tarjeta menta, "más recomendado")'), ('premium', 'Premium (tarjeta oscura)')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(blank=True, help_text='Un beneficio por línea — cada línea se muestra como un ítem con tilde en la tarjeta.'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(help_text='Nombre corto/etiqueta mostrada en mayúsculas arriba del título (ej. "Plan Lumbar").', max_length=150),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='tier',
            field=models.CharField(choices=[('plan1', 'Plan de membresía 1'), ('plan2', 'Plan de membresía 2'), ('plan3', 'Plan de membresía 3')], help_text='Identificador fijo del plan (no editable desde el admin).', max_length=20, unique=True),
        ),
    ]
