# Generated by Django 4.2.21 on 2026-09-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membershipplan_badge_membershipplan_cta_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='grace_days',
            field=models.PositiveIntegerField(default=5, help_text='Días de gracia con acceso mantenido después de un cobro fallido, mientras Mercado Pago reintenta el cobro. 0 = sin período de gracia (se pierde el acceso apenas falla el cobro).'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=7, help_text='Días de prueba gratuita antes del primer cobro. 0 = sin período de prueba.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_ends_at',
            field=models.DateTimeField(blank=True, help_text='Fin del período de gracia tras un cobro fallido — mientras esta fecha no haya pasado, el acceso se mantiene aunque ends_at ya haya pasado. Se completa al fallar un cobro (start_grace) y se limpia al cobrar con éxito (clear_grace).', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Fin del período de prueba gratuita. No afecta el acceso todavía (Fase 5A).', null=True),
        ),
    ]
