# Generated by Django 4.2.21 on 2026-09-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_membershipplan_grace_days_membershipplan_trial_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Marca la suscripción creada por la prueba gratuita de 7 días. No se edita a mano.'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trial', True)), fields=('user',), name='one_trial_subscription_per_user'),
        ),
    ]
