# Generated by Django 4.2.21 on 2026-09-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_subscription_is_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_charge_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_charge_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mp_init_point',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mp_payer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mp_preapproval_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mp_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Suscripción paga que reemplazó a esta prueba gratuita.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_trials', to='memberships.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Prueba'), ('active', 'Activa'), ('past_due', 'Pago vencido'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('pending', 'Pendiente de pago')], default='trial', max_length=20),
        ),
    ]
