# Generated by Django 4.2.21 on 2026-09-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_subscription_mp_preapproval_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mp_authorized_payment_id', models.CharField(db_index=True, max_length=100)),
                ('mp_payment_id', models.CharField(max_length=100, unique=True)),
                ('mp_payment_status', models.CharField(blank=True, default='', max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('outcome', models.CharField(choices=[('activated', 'Cobro aprobado — acceso extendido'), ('amount_mismatch', 'Monto/moneda no coincide — revisar a mano'), ('grace_started', 'Cobro fallido — período de gracia iniciado'), ('grace_running', 'Cobro fallido — gracia ya en curso'), ('past_due', 'Cobro fallido — gracia vencida, sin acceso'), ('first_charge_failed', 'Primer cobro fallido — nunca activada'), ('pending_charge', 'Cobro en proceso'), ('ignored', 'Sin efecto (suscripción no activa)')], max_length=30)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='memberships.subscription')),
            ],
            options={
                'verbose_name': 'Cobro de suscripción',
                'verbose_name_plural': 'Cobros de suscripción',
                'ordering': ['-created_at'],
            },
        ),
    ]
