# Generated by Django 4.2.21 on 2026-10-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_subscription_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='Suscripción mensual que esta suscripción anual reemplaza (cambio de plan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='memberships.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='upgrade_cancel_alerted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
