# Generated by Django 4.2.21 on 2026-09-12 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_content', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida'), ('refunded', 'Reembolsada')], default='pending', max_length=20)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='site_content.offering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra de propuesta',
                'verbose_name_plural': 'Compras de propuestas',
                'ordering': ['-created_at'],
            },
        ),
    ]
