# Generated by Django 4.2.21 on 2026-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeringpurchase',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offeringpurchase',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='offeringpurchase',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offeringpurchase',
            name='mp_preference_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offeringpurchase',
            name='mp_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='offeringpurchase',
            index=models.Index(fields=['mp_preference_id'], name='payments_of_mp_pref_bbb919_idx'),
        ),
    ]
