# Generated by Django 4.2.21 on 2026-08-10 16:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagline', models.CharField(blank=True, help_text='Frase breve de marca. Ej: eslogan mostrado en el hero y el pie de página.', max_length=200)),
                ('hero_headline', models.CharField(blank=True, help_text='Título principal de la portada.', max_length=200)),
                ('carla_bio', models.TextField(blank=True, help_text='Biografía de Carla. Separá párrafos con una línea en blanco.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('podcast_name', models.CharField(blank=True, max_length=150)),
                ('podcast_url', models.URLField(blank=True, help_text='Si se deja vacío, la sección de podcast no se muestra en la portada.')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menor valor aparece primero.')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='El precio no puede ser negativo.')])),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('payment_url_ars', models.URLField(blank=True, help_text='Link de Mercado Pago (u otro medio) para pagar en ARS.')),
                ('payment_url_usd', models.URLField(blank=True, help_text='Link de pago en USD. Opcional.')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'ordering': ['display_order', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='site_conten_is_acti_da4fe6_idx')],
            },
        ),
    ]
