# Generated by Django 4.2.21 on 2026-08-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='carla_bio_highlight',
            field=models.TextField(blank=True, help_text='Frase destacada de Carla, mostrada aparte de la biografía principal con un tratamiento visual propio (cita destacada). Ej: "ReCREO, me permite expresar mi esencia…".'),
        ),
    ]
