# Generated by Django 4.2.21 on 2026-09-03 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_seed_site_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menor valor aparece primero.')),
                ('author_name', models.CharField(max_length=150)),
                ('text', models.TextField(help_text='Texto de la reseña.')),
                ('rating', models.PositiveSmallIntegerField(help_text='Puntaje de 1 a 5 estrellas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['display_order', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='site_conten_is_acti_893580_idx')],
            },
        ),
    ]
