# Generated by Django 4.2.21 on 2026-09-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_seed_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=3000)),
                ('is_read', models.BooleanField(default=False, help_text='Carla lo tilda una vez que respondió la consulta.')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
