# Generated by Django 4.2.21 on 2026-09-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_video_access_level'),
        ('site_content', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='videos',
            field=models.ManyToManyField(blank=True, help_text='Videos que se desbloquean al comprar esta propuesta (opcional).', related_name='offerings', to='catalog.video'),
        ),
    ]
