# Generated by Django 4.2.21 on 2026-10-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0007_offering_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='carla_photo',
            field=models.ImageField(blank=True, help_text='Foto de la sección "Sobre Carla" de la portada. Usá una foto vertical (más alta que ancha), de al menos 800 px de ancho, con la cara cerca del centro: el marco es vertical (4:5) y recorta un poco arriba y abajo. Si la dejás vacía se muestra la "C".', upload_to='site/carla/', verbose_name='Foto de Carla'),
        ),
    ]
