# Generated by Django 4.2.21 on 2026-10-02 19:20

from django.db import migrations, models
import site_content.models
import site_content.storage


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0008_sitesettings_carla_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='deliverable',
            field=models.FileField(blank=True, help_text='Opcional. Un PDF que reciben quienes compran esta propuesta: lo descargan desde su cuenta y desde el link del mail de confirmación. Solo pueden descargarlo quienes lo compraron. Máximo 20 MB.', storage=site_content.storage.PrivateMediaStorage(), upload_to=site_content.models.offering_deliverable_upload_to, validators=[site_content.models.validate_pdf], verbose_name='PDF para descargar'),
        ),
    ]
