from django.test import TestCase

from site_content.models import Offering, SiteSettings


class SiteSettingsSingletonTests(TestCase):
    def test_load_creates_the_row_on_first_access(self):
        self.assertEqual(SiteSettings.objects.count(), 0)
        settings_obj = SiteSettings.load()
        self.assertEqual(settings_obj.pk, 1)
        self.assertEqual(SiteSettings.objects.count(), 1)

    def test_load_returns_the_same_row_every_time(self):
        first = SiteSettings.load()
        first.tagline = 'El éxito no tiene por qué costarte tu cuerpo'
        first.save()
        second = SiteSettings.load()
        self.assertEqual(second.pk, first.pk)
        self.assertEqual(second.tagline, first.tagline)

    def test_save_always_pins_pk_to_1(self):
        # Even a manually-constructed instance can't create a second row.
        rogue = SiteSettings(tagline='segunda fila')
        rogue.save()
        self.assertEqual(SiteSettings.objects.count(), 1)
        self.assertEqual(SiteSettings.objects.get().tagline, 'segunda fila')

    def test_delete_is_a_no_op(self):
        obj = SiteSettings.load()
        obj.delete()
        self.assertEqual(SiteSettings.objects.count(), 1)


class OfferingModelTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        offering = Offering.objects.create(name='Curso Neuro Postural', price=55000)
        self.assertEqual(offering.slug, 'curso-neuro-postural')

    def test_slug_disambiguated_on_collision(self):
        Offering.objects.create(name='Reset Express', price=24000)
        second = Offering.objects.create(name='Reset Express', price=24000)
        self.assertEqual(second.slug, 'reset-express-2')

    def test_negative_price_rejected(self):
        offering = Offering(name='Precio inválido', price=-100)
        with self.assertRaises(Exception):
            offering.full_clean()

    def test_payment_links_optional(self):
        offering = Offering.objects.create(name='Sin links todavía', price=1000)
        self.assertEqual(offering.payment_url_ars, '')
        self.assertEqual(offering.payment_url_usd, '')

    def test_default_ordering_by_display_order(self):
        second = Offering.objects.create(name='B', price=1, display_order=2)
        first = Offering.objects.create(name='A', price=1, display_order=1)
        self.assertEqual(list(Offering.objects.all()), [first, second])
