from django.test import TestCase

from site_content.models import ContactMessage, Offering, SiteSettings, Testimonial


class SiteSettingsSingletonTests(TestCase):
    def test_load_creates_the_row_on_first_access(self):
        # site_content's 0003 migration seeds the singleton on every fresh
        # DB (mirrors real production, where the row already exists) —
        # clear it here so this test can still exercise the actual "first
        # access ever" path it's named for.
        SiteSettings.objects.all().delete()
        self.assertEqual(SiteSettings.objects.count(), 0)
        settings_obj = SiteSettings.load()
        self.assertEqual(settings_obj.pk, 1)
        self.assertEqual(SiteSettings.objects.count(), 1)

    def test_load_returns_the_same_row_every_time(self):
        first = SiteSettings.load()
        first.tagline = 'El éxito no tiene por qué costarte tu cuerpo'
        first.save()
        second = SiteSettings.load()
        self.assertEqual(second.pk, first.pk)
        self.assertEqual(second.tagline, first.tagline)

    def test_save_always_pins_pk_to_1(self):
        # Even a manually-constructed instance can't create a second row.
        rogue = SiteSettings(tagline='segunda fila')
        rogue.save()
        self.assertEqual(SiteSettings.objects.count(), 1)
        self.assertEqual(SiteSettings.objects.get().tagline, 'segunda fila')

    def test_delete_is_a_no_op(self):
        obj = SiteSettings.load()
        obj.delete()
        self.assertEqual(SiteSettings.objects.count(), 1)


class OfferingModelTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        offering = Offering.objects.create(name='Curso Neuro Postural', price=55000)
        self.assertEqual(offering.slug, 'curso-neuro-postural')

    def test_slug_disambiguated_on_collision(self):
        Offering.objects.create(name='Reset Express', price=24000)
        second = Offering.objects.create(name='Reset Express', price=24000)
        self.assertEqual(second.slug, 'reset-express-2')

    def test_negative_price_rejected(self):
        offering = Offering(name='Precio inválido', price=-100)
        with self.assertRaises(Exception):
            offering.full_clean()

    def test_payment_links_optional(self):
        offering = Offering.objects.create(name='Sin links todavía', price=1000)
        self.assertEqual(offering.payment_url_ars, '')
        self.assertEqual(offering.payment_url_usd, '')

    def test_default_ordering_by_display_order(self):
        second = Offering.objects.create(name='B', price=1, display_order=2)
        first = Offering.objects.create(name='A', price=1, display_order=1)
        self.assertEqual(list(Offering.objects.all()), [first, second])


class TestimonialModelTests(TestCase):
    def test_rating_below_minimum_rejected(self):
        testimonial = Testimonial(author_name='Alguien', text='Texto', rating=0)
        with self.assertRaises(Exception):
            testimonial.full_clean()

    def test_rating_above_maximum_rejected(self):
        testimonial = Testimonial(author_name='Alguien', text='Texto', rating=6)
        with self.assertRaises(Exception):
            testimonial.full_clean()

    def test_valid_rating_accepted(self):
        testimonial = Testimonial(author_name='Alguien', text='Texto', rating=5)
        testimonial.full_clean()  # no debe lanzar

    def test_default_ordering_by_display_order(self):
        # migration 0005 seeds 5 rows on every fresh test DB (display_order
        # 1-5) — filter to just this test's own rows instead of relying on
        # Testimonial.objects.all() being exactly these two.
        second = Testimonial.objects.create(author_name='B', text='x', rating=5, display_order=102)
        first = Testimonial.objects.create(author_name='A', text='x', rating=5, display_order=101)
        self.assertEqual(list(Testimonial.objects.filter(pk__in=[first.pk, second.pk])), [first, second])

    def test_str_includes_author_and_rating(self):
        testimonial = Testimonial.objects.create(author_name='María', text='x', rating=5)
        self.assertIn('María', str(testimonial))
        self.assertIn('5', str(testimonial))


class ContactMessageModelTests(TestCase):
    def test_is_read_defaults_to_false(self):
        msg = ContactMessage.objects.create(name='Ana', email='ana@example.com', message='Hola')
        self.assertFalse(msg.is_read)

    def test_default_ordering_is_newest_first(self):
        older = ContactMessage.objects.create(name='Primero', email='a@example.com', message='x')
        newer = ContactMessage.objects.create(name='Segundo', email='b@example.com', message='x')
        self.assertEqual(list(ContactMessage.objects.all())[:2], [newer, older])

    def test_str_includes_name(self):
        msg = ContactMessage.objects.create(name='Ana', email='ana@example.com', message='Hola')
        self.assertIn('Ana', str(msg))
